server:
  port: 9002
spring:
  application:
    name: cloudalibaba-payment-service
  cloud:
    nacos:
      discovery:
        server-addr: 47.104.204.228:80

#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
