server:
  port: 3344

spring:
  application:
    name: cloud-config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/davisrain/springcloud-config.git
          search-paths:
            - springcloud-config
          timeout: 60
      #要拉取的分支名
      label:
        main
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: cloud-config-server
    prefer-ip-address: true

