server:
  port: 9527

spring:
  application:
    name: cloud-gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_route1              #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001      #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:                     #断言，路径相匹配的进行路由
            - Path=/payment/get/**

        - id: payment_route2
#          uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE
          filters:
            - AddRequestHeader=X-Ruquest-red,blue
          predicates:
            - Method=GET
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: cloud-gateway
    prefer-ip-address: true